name: CI on main (.NET 7.0.x on Ubuntu)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: scripts/BuildAndTest.ps1
      shell: pwsh
      working-directory: ./scripts
      run: |
        ./BuildAndTest.ps1
